### PR TITLE
update to 2.0.5.1

### PR DESCRIPTION
**Pull request by SapphireMH**

### CODE REVIEW

**Comment by Rad3d21** [comment]
Can you tell what the changes from the original marlin are globally ? Where is it made for ? BLtouch connected to probe pins ? SKR1.4 turbo ... which drivers, which printer ?

**Comment by SapphireMH** [comment]
> 
> 
> Can you tell what the changes from the original marlin are globally ? Where is it made for ? BLtouch connected to probe pins ? SKR1.4 turbo ... which drivers, which printer ?

@Rad3d21 Ive tried summarizing my setup below:

- skr 1.4 turbo using tmc2209 drivers with stall-guard enabled
- bltouch smart v3.1 connected to the dedicated probe pin
- anycubic ultrabase heated bed
- standard anet a8 hotend / frame / steppers / lcd
- everything running on 24v (the pid tunes etc)
- ive added a 3th preheat menu for PETG and added the ability to switch between PID tunes for the different materials i print with (different temps, different PIDS)
- Enabled power outage detection / recovery
- BTT 24v ups on p1_00 (PWRDET port)
- BTT relay v1.2 on p1_25 (E1DET port)
- no physical endstops
- emulated eeprom on SD card (instead of on flash)

If i forgot anything or if you have further questions let me know.

**Comment by SapphireMH** [comment]
Ooh and i reduced the homing feedrate (speed) so if my stall-guard messes up it doesn't crash at high speeds.

And i enabled fast homing so that both axis get homed at the same time.

**Comment by Rad3d21** [comment]
Ok. Thank you.
I've changed your config a little bit to support esp01s wifi dongle (esp3d)
I've got the skr1.4 turbo and tmc2209 and don't want to cut pins so will
also go for sensor less homing.
My printer is the Artillery Sidewinder X1 so AC heated bed. BLtouch is
ordered and will get it any day now. I wanted to use the designated pins
for it.
I guess your config comes close. That's cool!
I've added neopixel support but have to wait for the ledstick to test it.

Met vriendelijke groet,
Edwin

**Comment by SapphireMH** [comment]
@Rad3d21 please share your changes regarding the esp01s, i have the wifi module, but not yet the writer module. Will check this out soon.

Also you will still need to cut the diag pin on the Z axis driver, because it interferes with bltouch / z-endstop.

And you left your default email signature under your comment enabled.

Vriendelijke groet terug!

-Mike

**Comment by Rad3d21** [comment]
configuration.h 114: #define SERIAL_PORT 3
configuration_adv.h 2989 #define ESP3D_WIFISUPPORT

In
Users\.platformio\packages\framework-arduino-lpc176X\cores\Arduino\HARDWARESERIAL.h
You have to assign the pins in UART 3 in hardwareserial.h so your final
result is the following:

Line 107: PinCfg.Funcnum = 3;
Line 110: PinCfg.Pinnum = 28;
Line 111: PinCfg.Portnum = 4;
Line 113: PinCfg.Pinnum = 29;

First you can connect to the ESP3D wifi with pass 1234578 and connect to
192.168.0.1
You have to upload the files from:
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware/esp-01s
I did not upload the .bin because I was not sure which version it was. The
default on the ESP01 was 2.1.0.c26 and works fine.
Reload and connect again. Configure your wifi and baud rate 250000 and you
can issue commands.

for RGB
configuration.h 2218 #define NEOPIXEL_LED
#define NEOPIXEL_PIN P1_24

(but yet to verify this)

**Comment by Rad3d21** [comment]
I can confirm neopixel works. M150 B255 R0 U0 -> blue, M150 B0 R255 U0 ->
Red etc. M150 B50 R50 U50 -> white-ish.. M150 B255 R255 U255 = bright white

**Comment by SapphireMH** [comment]
@Rad3d21 Good to hear, thank you for the info.

**Pull request merged**
